# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1da3c4cb06030e2337fb32ac7c1f17eee9baabcc89f68bdd0ae2743bda31cea4f55ba327ef1eb2724ddcc22f9a4955c3d8b7cf28063d621c1ab2957809200ba

test:
  secret_key_base: 8e3f05ef79b48e53f3f3fd9194997690ad87fd0b496b4c40cecd94e2a47bdc46a54b96d2e3b3d8fde55e8f517ec75ab239a6dbf4ada01df4574efec89f38b650

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
